import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/ui";
import { AppShell, Navbar } from "@mantine/core";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="sm"
        navbar={<Navbar width={{ base: 300 }} height={`calc(100vh - 100px)`}>
          <Navbar.Section grow mt='md'>

          </Navbar.Section>
        </Navbar>}
        header={<Header links={[{ link: '/', label: 'home' }]} />
        }
      >
      </AppShell>
    </>
  );
};

export default Home;

